### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by SineSwiper**
You can ignore the Terraria files for now.  (GitHub won't let me be selective here.)

These include the following changes:
- Optimized several generators, including Basic's add_rooms and Perfect's @visited search in genmap.  Instead of taking 2-3 minutes for a 100x100 map, it's more like 5-10 seconds.
- Added ProgressBar::Quiet to most actions.  Ideally, there shouldn't be any blank spots for progress on even larger map creations.
- Added new Exporter.pm module for super-classing other Exporter modules; no need for one to have any subs except genmap
- Replaced Exporter/PNG with Exporter/Image, with support for JPG/GIF/GD files.  (Stub sub PNG in place for legacy apps.)
- New opt_reref sub to handle MapGen options better
- Removed some goto loops in place of while ones (needs to finish the rest that I can find)

### CODE REVIEW

**Comment by jettero** [comment]
I can't merge this because of your settings.xml.

“error: unable to create symlink MapGen/GeneratorPlugin/Terraria/settings.xml (File name too long)”

It's not clear to me that you even have a symlink version in the HEAD.  I don't think there should be settings files in there anyway, and I'm not at all sure why you think there should be.  Maybe move it to the root under contrib/ or something?  We can manifest a terraria-settings.xml file or what-have-you.

Anyway, please rebase and remove/readd (or fix) that so I can merge this and possibly post the merges back to github.

**Comment by jettero** [comment]
(I'm particularly excited about the efficiency updates.)

**Comment by SineSwiper** [comment]
Sorry, I was trying to get the symlink to work via Windows, but git doesn't support it yet.  Not sure why it's still listed as a symlink.  I'll delete and readd.

**Comment by SineSwiper** [comment]
I'll just close this request and use my master branch for the pull, since I've updated it to just have the original GRM files.

**Pull request closed without merging**
