### PR TITLE
New Stitch Generator module

### PR DESCRIPTION
**Pull request by SineSwiper**
This is the opposite of SubMap, allowing you to stitch together different maps into a larger map.  Tested it and it seems to work.  Just needs a little bit of code afterwards to join together pathways.

This module is part of a larger effort to create some Terraria generator modules.  Still working on that, but making good progress.  I've been working with BinaryConstruct, who made the TEdit world editor, to take his [settings.XML file](https://github.com/BinaryConstruct/Terraria-Map-Editor/blob/XmlSettings/TEdit/settings.xml) and make it standardized to use in other Terraria-related apps.

### CODE REVIEW

**Comment by jettero** [comment]
I didn't mean to close this and didn't actually merge it.  Github was fairly confused when I accidentally pushed to your repo.  If you check carefully, I really only merged the second pull request.

Before I pull this, I'd like some resolution to "Just needs a little bit of code afterwards to join together pathways." or (at the very least) an explanation of what that means.  I'd also like to see some tests so that I can be sure if I'm stomping around elsewhere I don't break this by mistake.

**Comment by SineSwiper** [comment]
Well, if you have a two maps made by GRM, say, 100x100 in size, and you stitch them together, the maps themselves are going to be two separate mazes.  In order to connect them, you (or rather, the module user) would need to find an appropriate connection point between the two, and "break a wall" to join it together.

Since there's a number of different ways to join together the maze, I left that as an exercise to the module user.

I'm using this to create multiple mazes of different types, and stitching them together for a single map.

**Comment by jettero** [comment]
I get what it's for.  I'm excited to include it.  Most of the generators are fairly automatic though.  I hoped it would have some of the post-stitching resolved, at least as options.  I'd also like to see tests for it.  I can pull it like this, if you feel like it's ready to go.  It's surely not going to hurt anything.

**Comment by SineSwiper** [comment]
I'm fine with putting in some tests first.  And maybe I can put in some code for the wall breaking, with a option for "none, one, or all walls".  I have to code the wall breaking at some point, anyway.

**Comment by jettero** [comment]
Sweet.  I look forward to both.

**Pull request merged**
