### PR TITLE
Added new Exporter.pm for better subclassing

### PR DESCRIPTION
**Pull request by SineSwiper**
Passes all of the tests.  Includes new Image.pm module.

### CODE REVIEW

**Comment by jettero** [comment]
I didn't forget about this.  They're killing me at work.  Tomorrow morning hopefully?

**Comment by SineSwiper** [comment]
No problem.  Working on the TEdit side in the meantime, anyway.

**Comment by jettero** [comment]
I pulled this.  Noticed an ancient bug in my stuff re: number-of-rooms from the editor's generator...

**Comment by SineSwiper** [comment]
Good deal.  Just need to make sure the ProgressBar is everywhere it needs to be and then add an option to turn it on.  There's also some minor edits to various things here and there.  I may just bundle those together, since the latter is going to be small.

**Pull request merged**
